CREATE TABLE boss (
  id INT PRIMARY KEY,
  name VARCHAR(500),
  location VARCHAR(500),
  is_optional BOOLEAN,
  health INT,
  drops VARCHAR(500),
  nearest_site_of_grace VARCHAR(500),
  damage_types VARCHAR(500),
  defense INT,
  stance INT,
  is_parryable BOOLEAN,
  critical_hit_vulnerability VARCHAR(500),
  negations JSON,
  resistances JSON,
  image1 VARCHAR(500),
  image2 VARCHAR(500),
  link VARCHAR(500),
  description TEXT,
  lore TEXT,
  attack_patterns TEXT,
  ng_plus_stats JSON,
  coordinates JSON
);




INSERT INTO boss (
  id, name, location, is_optional, health, drops, nearest_site_of_grace,
  damage_types, defense, stance, is_parryable, critical_hit_vulnerability,
  negations, resistances, image1, image2, link, description, lore, attack_patterns, ng_plus_stats, coordinates
) VALUES (
  1, 'Godfrey, First Elden Lord (Golden Shade)', 'Leyndell, Royal Capital', FALSE, 7099, 
  '80,000 Runes, Talisman Pouch (NG Only)', 'West Capital Rampart', 
  'Standard, Pierce, Magic, Fire', 114, 120, FALSE, 'Stance Broken', 
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 0, "Magic": 20, "Fire": 20, "Lightning": 0, "Holy": 40}', 
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "552/842/1299", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godfrey-first-elden-lord-1-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3495488/92415334758b7ae55ed673be4abd5fdc.png/show', 
  'https://www.youtube.com/watch?v=t330LuQDEZk&t=55s&ab_channel=Das7ardly',
  'Spectral shade of Godfrey encountered in Leyndell, Royal Capital.',
  'After reducing the boss\'s health to ~80%, he transforms into a more powerful version.',
  '{"Ground Stomp": "Raise foot and slam, sending rocks forward in a cone.", "Two-handed Axe Slam": "Fastest move, followed by axe swings.", "Jumping Axe Throw": "Leaps and throws axe, then dives onto it.", "One-handed Overhead Slam": "Swings axe overhead and slams it to the ground."}',
  '{"ng": {"hp": 7099, "defense": 114, "runes": 80000}, "ng_plus": {"hp": 8895, "defense": 118, "runes": 240000}}',
  '{"lat": 35.6895, "lng": 139.6917}' 
),
(
  2, 'Red Wolf of Radagon', 'Academy of Raya Lucaria', TRUE, 1200,
  'Memory Stone', 'Main Academy Gate',
  'Magic, Physical', 95, 110, FALSE, 'Stance Broken',
  '{"Standard": 20, "Slash": 20, "Strike": 10, "Pierce": 10, "Magic": 0, "Fire": 10, "Lightning": 30, "Holy": 40}',
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "410/570/890", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/red-wolf-of-radagon-1-hq-elden-ring-wiki-guide.jpg',
  'https://img.game8.co/3492542/775a4931d3156d9048f683bdf2aa528a.png/show',
  'https://www.youtube.com/watch?v=o89qeVth4iU&ab_channel=PowerStanik',
  'The Red Wolf of Radagon is a Boss in Elden Ring. This large, red-furred wolf wields a magical sword and is known for its agility and powerful attacks.',
  'This boss guards the entrance to the Debate Parlor and must be defeated to proceed further into the academy.',
  '{"Sword Swipe": "Swings its magical sword in a wide arc.", "Leap Attack": "Leaps into the air and slams down with its sword.", "Magic Burst": "Emits a burst of magic energy from its body."}',
  '{"ng": {"hp": 1200, "defense": 95, "runes": 14000}, "ng_plus": {"hp": 1560, "defense": 98, "runes": 42000}}',
  '{"lat": 34.0522, "lng": -118.2437}'  
),
(
  3, 'Malenia, Blade of Miquella', 'Elphael, Brace of the Haligtree', TRUE, 33210,
  'Malenia\'s Great Rune, Remembrance of the Rot Goddess', 'Haligtree Roots',
  'Standard, Pierce', 143, 120, FALSE, 'Stance Broken',
  '{"Standard": 0, "Slash": 0, "Strike": 0, "Pierce": 0, "Magic": 40, "Fire": 40, "Lightning": 40, "Holy": 40}',
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "552/842/1299", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/malenia,-blade-of-miquella.jpg',
  'https://img.game8.co/3502064/d9c3aa6843b32c9b18d2d500b30f95cb.png/show',
  'https://www.youtube.com/watch?v=NIh_1iVcMng&ab_channel=Das7ardly',
  'Malenia, Blade of Miquella is a Boss in Elden Ring. Malenia is one of the most challenging bosses, known for her agility, healing abilities, and powerful attacks.',
  'Malenia is encountered in Elphael, Brace of the Haligtree. She is Miquella\'s twin and the wielder of the Scarlet Rot.',
  '{"Waterfowl Dance": "Leaps into the air and slashes multiple times in a flurry of attacks.", "Scarlet Aeonia": "Transforms into a blooming flower that causes Scarlet Rot build-up.", "Gliding Slash": "Glides across the ground, slashing with her blade.", "Healing Slash": "Recovers health with every hit landed on the player."}',
  '{"ng": {"hp": 33210, "defense": 143, "runes": 480000}, "ng_plus": {"hp": 42403, "defense": 147, "runes": 1440000}}',
  '{"lat": 51.5074, "lng": -0.1278}'  
),
(
  4, 'Rennala, Queen of the Full Moon', 'Raya Lucaria Academy', TRUE, 3493,
  '40,000 Runes (NG), Remembrance of the Full Moon Queen, Great Rune of the Unborn', 'Debate Parlor',
  'Standard, Magic, Fire', 109, 0, FALSE, 'Stance Broken',
  '{"Standard": -10, "Slash": -10, "Strike": 0, "Pierce": -10, "Magic": 80, "Fire": 20, "Lightning": 20, "Holy": 20}', 
  '{"Poison": 326, "Scarlet Rot": 326, "Hemorrhage": 326, "Frostbite": 326, "Sleep": "Immune", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rennala-1-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3492749/c18f4a3bf0a360ed8b1d7f9ec8164a02.png/show', 
  'https://www.youtube.com/watch?v=Oz1TpUVjapw&ab_channel=sirmicho',
  'Rennala is a powerful sorceress encountered in the Raya Lucaria Academy. She is known for her powerful magic attacks and the ability to summon spirits.',
  'Rennala is the head of the Carian Royal family and the erstwhile leader of the Academy. She becomes a friendly NPC after being defeated.',
  '{"Phase 1": {"Bubble Shield": "Protected by a bubble shield. Break it by hitting golden scholars."}, "Phase 2": {"Full Moon": "Casts a powerful full moon spell."}}',
  '{"ng": {"hp": 3493, "defense": 109, "runes": 40000}, "ng_plus": {"hp": 5319, "defense": 117, "runes": 120000}}',
  '{"lat": 51.5074, "lng": -0.1278}'
),
(
  5, 'Ancestor Spirit', 'Siofra River', TRUE, 4393,
  '13,000 Runes, Ancestral Follower Ashes', 'Siofra River Bank',
  'Standard, Magic', 107, 120, FALSE, 'Stance Broken',
  '{"Standard": 0, "Slash": -10, "Strike": 0, "Pierce": 0, "Magic": 20, "Fire": -20, "Lightning": 0, "Holy": -20}', 
  '{"Poison": 1140, "Scarlet Rot": 1140, "Hemorrhage": 1140, "Frostbite": 1140, "Sleep": "Immune", "Madness": "Immune"}',
  'https://i.redd.it/rpgay8nmbyo81.jpg', 
  'https://img.game8.co/3506353/f65b7f3f62e1d20a433936518f9c8dce.png/show', 
  'https://www.youtube.com/watch?v=tFHy3szjA7k&ab_channel=BonfireVN',
  'Ancestor Spirit is a Great Enemy Boss in Elden Ring, encountered in the Hallowhorn Grounds in Siofra River. This boss resembles a spectral deer and is known for its graceful, ethereal movements.',
  'Ancestor Spirit is a mystical entity worshipped by the ancestral followers of Siofra River, embodying the spirits of their ancestors.',
  '{"Antler Swing": "Swings its antlers along the ground.", "Hoof Slam": "Rises up on its hind legs and slams down.", "Airborne Spirit Vapor": "Jumps into the air and breathes damaging vapor."}',
  '{"ng": {"hp": 4393, "defense": 107, "runes": 13000}, "ng_plus": {"hp": 8105, "defense": 117, "runes": 52000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  
),
(
  6, 'Starscourge Radahn', 'Caelid', TRUE, 9572,
  '70,000 Runes, Remembrance of the Starscourge, Radahn\'s Great Rune', 'Chamber Outside the Plaza',
  'Standard, Pierce, Magic', 113, 200, FALSE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 0, "Magic": 20, "Fire": 20, "Lightning": 20, "Holy": 40}', 
  '{"Poison": 334, "Scarlet Rot": 243, "Hemorrhage": 334, "Frostbite": 334, "Sleep": 548, "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/radahn-2-hq-enemy-elden-ring-wiki.jpg', 
  'https://img.game8.co/3493843/fee93a776ed2437654747ec45d3e9282.png/show', 
  'https://www.youtube.com/watch?v=Ee83r-3aKbw&ab_channel=wuh1',
  'Starscourge Radahn is one of the mightiest demigods, afflicted with Scarlet Rot, causing him to be in a feral rage. Found in Caelid, he is an optional boss but must be defeated to access Nokron, Eternal City.',
  'The Red Lion General wielded gravitational powers learned in Sellia during his younger days. He never wanted to abandon his beloved but scrawny steed.',
  '{"Phase 1": {"Arrow Barrage": "Shoots a barrage of arrows from the sky.", "Gravity Pull": "Pulls players towards him with gravitational force."}, "Phase 2": {"Meteor Crash": "Leaps into the air and crashes down like a meteor.", "Gravity Wave": "Creates a massive wave of gravitational energy."}}',
  '{"ng": {"hp": 9572, "defense": 113, "runes": 70000}, "ng_plus": {"hp": 12405, "defense": 118, "runes": 210000}}',
  '{"lat": 34.0522, "lng": -118.2437}' 
),
(
  7, 'Magma Wyrm Makar', 'Ruin-Strewn Precipice', TRUE, 7141,
  '24,000 Runes, Magma Wyrm\'s Scalesword, Dragon Heart', 'Ruin-Strewn Precipice Overlook',
  'Standard, Slash, Strike, Fire', 109, 120, FALSE, 'Stance Broken',
  '{"Standard": 10, "Slash": 35, "Strike": 10, "Pierce": 10, "Magic": 40, "Fire": 80, "Lightning": 40, "Holy": 40}', 
  '{"Poison": 534, "Scarlet Rot": 534, "Hemorrhage": 534, "Frostbite": 1150, "Sleep": 237, "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/magma-wyrm-3-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3493381/bace042869584f5fae0e41a48a7b8a9e.png/show', 
  'https://www.youtube.com/watch?v=ONBCt9mLY98&ab_channel=Shirrako',
  'Magma Wyrm Makar is a Great Enemy Boss in Elden Ring, encountered in the Ruin-Strewn Precipice. Once a human, Makar was transformed into a lesser dragon for the sin of Dragon Communion.',
  'Makar was transformed into a Magma Wyrm as a punishment for the sin of Dragon Communion, and now guards the path to Altus Plateau.',
  '{"Phase 1": {"Magma Spit": "Spits magma in a straight line.", "Tail Swipe": "Swings its tail in an arc."}, "Phase 2": {"Magma Breath": "Breathes magma in a wide arc.", "Roar": "Roars, causing a shockwave."}}',
  '{"ng": {"hp": 7141, "defense": 109, "runes": 24000}, "ng_plus": {"hp": 10875, "defense": 117, "runes": 72000}}',
  '{"lat": 35.6762, "lng": 139.6503}'  
),
(
  8, 'Royal Knight Loretta', 'Caria Manor', TRUE, 4214,
  '10,000 Runes, Loretta\'s Greatbow, Ash of War: Loretta\'s Slash', 'Manor Upper Level',
  'Standard, Strike, Pierce, Magic', 107, 80, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 10, "Magic": 40, "Fire": 40, "Lightning": 0, "Holy": 20}', 
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "Immune", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/royal-knight-loretta-1-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3493078/ee5a8669ecf3bf861082c6456c4fd9b2.png/show', 
  'https://www.youtube.com/watch?v=kZI0T-C0wB4&ab_channel=Kyto66',
  'Royal Knight Loretta is the spirit of a knight riding atop her steed, wielding a polearm and utilizing powerful glintstone sorceries to punish trespassers in Caria Manor.',
  'Loretta was once a royal Carian Knight, now protecting Ranni from trespassers at the Caria Manor.',
  '{"Side Swing": "Swings her sickle in various directions.", "Stab": "Stabs the blade of her sickle in various directions.", "Rearing Swing": "Rears up and slams her sickle down diagonally.", "Bash Swing": "Steps back and bashes its head forward as she swings her sickle."}',
  '{"ng": {"hp": 4214, "defense": 107, "runes": 10000}, "ng_plus": {"hp": 7774, "defense": 117, "runes": 40000}}',
  '{"lat": 35.6586, "lng": 139.7454}'
),
(
  9, 'Leonine Misbegotten', 'Castle Morne', TRUE, 2198,
  '3,800 Runes, Grafted Blade Greatsword', 'Beside the Rampart Gaol',
  'Standard, Slash, Strike, Pierce', 103, 80, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 0, "Strike": 10, "Pierce": 10, "Magic": 20, "Fire": 0, "Lightning": 20, "Holy": 20}', 
  '{"Poison": 316, "Scarlet Rot": 316, "Hemorrhage": 316, "Frostbite": 316, "Sleep": 316, "Madness": "Immune"}',
  'https://cdn.vox-cdn.com/thumbor/OGO9PLwc7_wk90wVw9fATk0puz0=/0x0:1920x1080/1200x800/filters:focal(807x387:1113x693)/cdn.vox-cdn.com/uploads/chorus_image/image/73394919/Leonine_header_image.0.jpg', 
  'https://img.game8.co/3494223/3cc5a02a18c464e448be487165d4bb94.png/show', 
  'https://www.youtube.com/watch?v=UQG0D86gWKc&ab_channel=BossFightDatabase',
  'Leonine Misbegotten is a Great Enemy Boss found in Castle Morne. This feral humanoid with bestial features wields a large greatsword and is extremely aggressive.',
  'This boss stole the treasured sword of Castle Morne, and defeating it is not required to advance the main story.',
  '{"Lunging Slash": "Jumps towards and slashes with its sword.", "Running Slash": "Runs towards and slashes with its sword.", "Sideswipe": "Runs past and slashes.", "Barbaric Roar": "Roars, causing a small area of effect damage."}',
  '{"ng": {"hp": 2198, "defense": 103, "runes": 3800}, "ng_plus": {"hp": 5179, "defense": 117, "runes": 19000}}',
  '{"lat": 34.0522, "lng": -118.2437}'  
),
(
  10, 'Golden Hippopotamus', 'Shadow Keep', TRUE, 33866,
  '200,000 Runes, Aspects of the Crucible: Thorns, x2 Scadutree Fragments', 'Shadow Keep Main Gate',
  'Standard', 100, 120, FALSE, 'Stance Broken',
  '{"Standard": 20, "Slash": 20, "Strike": 20, "Pierce": 20, "Magic": 40, "Fire": 40, "Lightning": 20, "Holy": 40}', 
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "Immune", "Madness": "Immune"}',
  'https://static1.thegamerimages.com/wordpress/wp-content/uploads/wm/2024/06/mixcollage-29-jun-2024-06-36-pm-5577.jpg', 
  'https://img.game8.co/3915113/f869ac447c288e658926538112821b29.png/show', 
  'https://www.youtube.com/watch?v=XZvoHdKdK7M&ab_channel=BossFightDatabase',
  'Golden Hippopotamus is a Great Enemy Boss found near the foot of the giant Marika Statue in Shadow Keep. It is an optional boss.',
  'The Golden Hippopotamus generates golden thorns when its health drops below 50%, making it more dangerous in the second phase.',
  '{"Belly Slam": "Drops its belly to the ground, damaging an area beneath it.", "Fanged Charge": "Charges forward with its mouth wide open.", "Golden Thorns": "Generates golden thorns on its back and head when health drops to 50%."}',
  '{"ng": {"hp": 33866, "defense": 100, "runes": 200000}, "ng_plus": {"hp": 36475, "defense": 110, "runes": 600000}}',
  '{"lat": 51.5074, "lng": -0.1278}'  
),
(
  11, 'Rellana, Twin Moon Knight', 'Castle Ensis', FALSE, 29723,
  '180,000 Runes, Remembrance of the Twin Moon Knight', 'Castle Lord\'s Chamber',
  'Standard, Pierce, Magic, Fire', 120, 200, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 0, "Pierce": 20, "Magic": 30, "Fire": 30, "Lightning": 20, "Holy": 20}', 
  '{"Poison": 100, "Scarlet Rot": 100, "Hemorrhage": 100, "Frostbite": 100, "Sleep": "Immune", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rellana_twin_moon_knight2.png', 
  'https://img.game8.co/3915166/1efc8a2fb703d44e6ffcfc0789394bea.png/show', 
  'https://www.youtube.com/watch?v=6a1gcH6PB8I&ab_channel=DraKulisCinematicGaming',
  'Rellana, Twin Moon Knight is a formidable boss found in Castle Ensis, known for her dual-wielding light greatswords infused with glintstone and Mesmer\'s Flame.',
  'Rellana, a princess of the Carian family and sister of Rennala, Queen of the Full Moon, is a guardian of Castle Ensis and must be defeated to progress in the Shadow of the Erdtree DLC.',
  '{"Blade Dance": "A series of fast slashes and stabs.", "Glintblade Phalanx": "Summons glintblades that track the player.", "Giant Carian Greatsword": "A massive magic-infused blade attack."}',
  '{"ng": {"hp": 29723, "defense": 120, "runes": 180000}, "ng_plus": {"hp": 32007, "defense": 130, "runes": 540000}}',
  '{"lat": 51.509865, "lng": -0.118092}'
),
(
  12, 'Divine Beast Dancing Lion', 'Belurat, Tower Settlement', TRUE, 22571,
  '90,000 Runes, Remembrance of the Dancing Lion, Divine Beast Head', 'Stagefront Site of Grace',
  'Standard, Magic, Lightning, Holy, Frostbite', 120, 120, FALSE, 'Stance Broken',
  '{"Standard": 30, "Slash": 40, "Strike": 30, "Pierce": 10, "Magic": 40, "Fire": 0, "Lightning": 40, "Holy": 40}', 
  '{"Poison": 403, "Scarlet Rot": 293, "Hemorrhage": 293, "Frostbite": 659, "Sleep": "Immune", "Madness": "Immune"}',
  'https://i.ytimg.com/vi/AkuOu10PT0k/maxresdefault.jpg', 
  'https://img.game8.co/3912622/bb80c637da251796ca023bbbeec1e290.png/show', 
  'https://www.youtube.com/watch?v=Jgf8LPvHWrM&ab_channel=WoWQuests',
  'Divine Beast Dancing Lion is a powerful and fast boss that uses diverse elemental attacks and is found in Belurat, Tower Settlement. This is an optional boss in the Shadow of the Erdtree DLC.',
  'The Divine Beast Dancing Lion is based upon the Chinese tradition of Lion Dancing.',
  '{"Phase 1": {"Wind Blast": "Blows a long burst of wind.", "Leaping Bite": "Leaps through the air and bites."}, "Phase 2": {"Lightning Bolt": "Summons a lightning bolt.", "Ice Stomp": "Summons ice shards."}}',
  '{"ng": {"hp": 22571, "defense": 120, "runes": 90000}, "ng_plus": {"hp": 24336, "defense": 130, "runes": 270000}}',
  '{"lat": 35.6895, "lng": 139.6917}' 
),
(
  13, 'Messmer the Impaler', 'Shadow Keep, Specimen Storehouse', FALSE, 38981,
  '400,000 Runes, Remembrance of the Impaler, Messmer\'s Kindling', 'Dark Chamber Entrance',
  'Standard, Pierce, Fire', 120, 120, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 0, "Magic": 20, "Fire": 50, "Lightning": 50, "Holy": 50}', 
  '{"Poison": 60, "Scarlet Rot": 60, "Hemorrhage": 80, "Frostbite": 80, "Sleep": "Immune", "Madness": "Immune"}',
  'https://static1.srcdn.com/wordpress/wp-content/uploads/2024/02/elden-ring-shadow-of-the-erdtree-dlc-messmer-the-impaler.jpg', 
  'https://img.game8.co/3914837/f450832d5f034ff04667cbbb80244506.png/show', 
  'https://www.youtube.com/watch?v=rqRqzwJQAiA&ab_channel=Brunoborne',
  'Messmer the Impaler is a Demigod Boss in Elden Ring found in the Shadow Keep. He uses fire-based attacks and a large spear. Not an optional boss, players need to defeat him to advance in the Shadow of the Erdtree DLC.',
  'Messmer performs a ritualistic act during the battle, transforming into a more powerful form in the second phase.',
  '{"Phase 1": {"Spear Thrust": "Thrusts spear toward you.", "Fireball": "Summons a fireball."}, "Phase 2": {"Explosive Bite": "Transforms into a snake and explodes."}}',
  '{"ng": {"hp": 38981, "defense": 120, "runes": 400000}, "ng_plus": {"hp": 41094, "defense": 130, "runes": 1200000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  
),
(
  14, 'Margit, The Fell Omen', 'Stormhill', FALSE, 4208,
  '12,000 Runes, Talisman Pouch', 'Castleward Tunnel',
  'Standard, Slash, Pierce, Holy', 80, 60, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 10, "Magic": 20, "Fire": 20, "Lightning": 20, "Holy": 40}', 
  '{"Poison": 252, "Scarlet Rot": 252, "Hemorrhage": 252, "Frostbite": 112, "Sleep": "Immune", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/margit-3-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3485085/b9cdc391a87914355ff4c009ceafa469.png/show', 
  'https://www.youtube.com/watch?v=qV9EQ766elM&ab_channel=SweetGames',
  'Margit, The Fell Omen, is the first major boss that players encounter in Elden Ring, located in Stormhill. This encounter tests the players\' readiness for the challenges ahead in the game.',
  'Margit serves as the initial gatekeeper boss, preventing unprepared players from progressing further into the Lands Between.',
  '{"Hammer Strike": "Summons a golden hammer to slam the ground.", "Daggers": "Throws multiple golden daggers.", "Leap Attack": "Leaps and strikes with his staff."}',
  '{"ng": {"hp": 4208, "defense": 80, "runes": 12000}, "ng_plus": {"hp": 5802, "defense": 84, "runes": 36000}}',
  '{"lat": 51.5074, "lng": -0.1278}'  -- Exemple de coordonnées pour Londres, à remplacer par les vraies coordonnées
),
(
  15, 'Midra, Lord of Frenzied Flame', 'Midra\'s Manse', TRUE, 47171,
  '410,000 Runes, Remembrance of the Lord of Frenzied Flame', 'Second Floor Chamber',
  'Standard, Pierce, Fire', 80, 120, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 0, "Magic": 20, "Fire": 50, "Lightning": 50, "Holy": 50}', 
  '{"Poison": 60, "Scarlet Rot": 60, "Hemorrhage": 80, "Frostbite": 80, "Sleep": "Immune", "Madness": "Immune"}',
  'https://cdn.vox-cdn.com/thumbor/LPOXO92he1RiMU-v95t3z7WE3eY=/0x0:1920x1080/1200x800/filters:focal(807x387:1113x693)/cdn.vox-cdn.com/uploads/chorus_image/image/73442743/eldenring_guide_midraboss_header.0.jpg', 
  'https://img.game8.co/3915309/7d74fca5b7c4cf09a202b8591ea8ef7c.png/show', 
  'https://www.youtube.com/watch?v=H8cFv94jo6o&ab_channel=WoWQuests',
  'Midra, Lord of Frenzied Flame, is an optional boss in Elden Ring found in Midra\'s Manse. Known for his fire-based attacks and high damage output, Midra poses a significant challenge.',
  'Midra wields a spear and relies heavily on fire attacks. He is known to explode in flames after being staggered, making him a formidable opponent.',
  '{"Flame Strands": "Summons multiple flame strands.", "Triple Spear Swing": "Swings spear three times.", "Flame Explosion": "Causes a large flame explosion."}',
  '{"ng": {"hp": 47171, "defense": 80, "runes": 410000}, "ng_plus": {"hp": 49002, "defense": 90, "runes": 1230000}}',
  '{"lat": 51.509865, "lng": -0.118092}'  -- Exemple de coordonnées pour Londres, à remplacer par les vraies coordonnées
),
(
  16, 'Promised Consort Radahn', 'Enir-Ilim', FALSE, 46134,
  '500,000 Runes, Remembrance of a God and a Lord', 'Divine Gate Front Staircase',
  'Standard, Pierce, Fire', 120, 200, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 0, "Pierce": 10, "Magic": 20, "Fire": 30, "Lightning": 20, "Holy": 40}', 
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "Immune", "Madness": "Immune"}',
  'https://assetsio.gnwcdn.com/elden-ring-sote-radahn-1.png', 
  'https://img.game8.co/3915608/e2bb0db7d4bbf1118fdab0f94d6aca80.png/show', 
  'https://www.youtube.com/watch?v=8Oj4zKLhHmA&ab_channel=ML',
  'Promised Consort Radahn is an imposing, fully armored humanoid enemy adorned in red and gold, wielding two colossal swords. He is not an optional boss as players need to defeat him to advance in Elden Ring: Shadow of the Erdtree.',
  'Promised Consort Radahn transforms into Radahn, Consort of Miquella, upon reaching 60% health, introducing new divine abilities.',
  '{"Gravity Cyclone": "Leaps through the air while spinning with swords, ending in an explosion.", "Bloodflame Slash": "Swings sword to create bloodflames.", "Starcaller Cry": "Pulls you with gravity and causes rock spikes.", "Triple Sword Swing": "Swings swords thrice in close range."}',
  '{"ng": {"hp": 46134, "defense": 120, "runes": 500000}, "ng_plus": {"hp": 47579, "defense": 130, "runes": 1500000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  -- Exemple de coordonnées pour Tokyo, à remplacer par les vraies coordonnées
),
(
  17, 'Radahn, Consort of Miquella', 'Enir-Ilim', FALSE, 46134,
  '500,000 Runes, Remembrance of a God and a Lord', 'Divine Gate Front Staircase',
  'Standard, Pierce, Fire, Magic', 120, 120, TRUE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 0, "Pierce": 10, "Magic": 20, "Fire": 30, "Lightning": 20, "Holy": 40}', 
  '{"Poison": 733, "Scarlet Rot": 733, "Hemorrhage": 733, "Frostbite": 733, "Sleep": "Immune", "Madness": "Immune"}',
  'https://static1.thegamerimages.com/wordpress/wp-content/uploads/wm/2024/07/elden-ring-tm-_20240629131243-cropped.jpg', 
  'https://cdn.discordapp.com/attachments/1245798920555200638/1263783766363603004/fin_4.png?ex=669b7dd9&is=669a2c59&hm=70f35a636663f4894d4c4ad915f33df4c4466a881ce2cb994635ef88d3913611&', 
  'https://www.youtube.com/watch?v=1vTHMaRag4s&ab_channel=TarnishedSoul',
  'Radahn, Consort of Miquella, is the enhanced form of Promised Consort Radahn, encountered after reducing his health to ~60%. This form retains previous attacks while adding new divine abilities, making him more challenging.',
  'Radahn transforms into a more powerful version with divine abilities, making him a formidable opponent in Elden Ring: Shadow of the Erdtree.',
  '{"Gravity Cyclone": "Leaps through the air while spinning with swords, ending in an explosion.", "Bloodflame Slash": "Swings sword to create bloodflames.", "Starcaller Cry": "Pulls you with gravity and causes rock spikes.", "Holy Meteor Crash": "Leaps into the air and crashes down with a glorious explosion."}',
  '{"ng": {"hp": 46134, "defense": 120, "runes": 500000}, "ng_plus": {"hp": 47579, "defense": 130, "runes": 1500000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  -- Exemple de coordonnées pour Tokyo, à remplacer par les vraies coordonnées
),
(
  18, 'Maliketh, the Black Blade', 'Crumbling Farum Azula', FALSE, 10620,
  '220,000 Runes, Remembrance of the Black Blade', 'Beside the Great Bridge',
  'Standard, Slash, Pierce, Magic, Holy', 120, 80, TRUE, 'Stance Broken',
  '{"Standard": 35, "Slash": 35, "Strike": 35, "Pierce": 35, "Magic": 40, "Fire": 40, "Lightning": 40, "Holy": 80}', 
  '{"Poison": 351, "Scarlet Rot": 351, "Hemorrhage": 574, "Frostbite": 574, "Sleep": 2277, "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/maliketh-the-black-blade-4k.jpg', 
  'https://img.game8.co/3500208/06655798c7169d4d23d057461129619b.png/show', 
  'https://www.youtube.com/watch?v=lLr8KuOM0hA&ab_channel=neojb1989',
  'Maliketh, the Black Blade, is a two-phase boss encountered in Crumbling Farum Azula. The first phase is the Beast Clergyman, and the second phase reveals Maliketh, the Black Blade.',
  'Maliketh guards the Rune of Death and transforms into a more powerful version with divine abilities upon reaching half health.',
  '{"Phase 1": {"Ground Stab": "Lunges forward to stab the ground.", "Bestial Sling": "Throws rocks at the player."}, "Phase 2": {"Black Blade": "Swings sword causing frontal cone area damage.", "Destined Death": "Inflicts damage over time and reduces max health."}}',
  '{"ng": {"hp": 10620, "defense": 120, "runes": 220000}, "ng_plus": {"hp": 11694, "defense": 123, "runes": 440000}}',
  '{"lat": 36.1126, "lng": -115.1728}'  -- Exemple de coordonnées pour Las Vegas, à remplacer par les vraies coordonnées
),
 (
  19, 'Dragonkin Soldier of Nokstella', 'Ainsel River', TRUE, 4372,
  '12,000 Runes, Frozen Lightning Spear', 'Ainsel River Downstream',
  'Standard, Lightning', 106, 120, FALSE, 'Stance Broken',
  '{"Standard": 10, "Slash": 0, "Strike": 10, "Pierce": 10, "Magic": 20, "Fire": 20, "Lightning": 40, "Holy": 20}', 
  '{"Poison": 526, "Scarlet Rot": 526, "Hemorrhage": 526, "Frostbite": 1131, "Sleep": "Immune", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragonkin-soldier-nokstella-2-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3519276/8e3228504a1f95a21a5a70f6cdcb109c.png/show', 
  'https://www.youtube.com/watch?v=yTFG73sBSXw&ab_channel=Shirrako',
  'The Dragonkin Soldier of Nokstella is a Greater Foe Boss found in Ainsel River. This huge, draconic humanoid guards an ancient throne beneath the eternal city of Nokstella.',
  'The Dragonkin Soldiers were created in the Eternal City, utilizing ice lightning as their primary weapon.',
  '{"Phase 1": {"Standard Attacks": "Uses basic physical attacks."}, "Phase 2": {"Lightning Explosion": "Charges with lightning and creates an explosion."}}',
  '{"ng": {"hp": 4372, "defense": 106, "runes": 12000}, "ng_plus": {"hp": 9176, "defense": 117, "runes": 48000}}',
  '{"lat": 35.6586, "lng": 139.7454}'  -- Exemple de coordonnées pour Tokyo, à remplacer par les vraies coordonnées
),
(
  20, 'Morgott the Omen King', 'Leyndell, Royal Capital', FALSE, 10399,
  '120,000 Runes, Remembrance of the Omen King, Morgott\'s Great Rune, Talisman Pouch (NG only if Margit not defeated)', 'Queen\'s Bedchamber',
  'Slash, Pierce, Holy', 114, 80, TRUE, 'Stance Broken',
  '{"Standard": 0, "Slash": -10, "Strike": 0, "Pierce": 0, "Magic": 0, "Fire": 0, "Lightning": 0, "Holy": 40}', 
  '{"Poison": 337, "Scarlet Rot": 337, "Hemorrhage": 337, "Frostbite": 337, "Sleep": 552, "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/morgott-omen-king-1-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3495928/5938108c34f5090f6c4209963b06859c.png/show', 
  'https://www.youtube.com/watch?v=bTONwIzHhtw&ab_channel=Pappayay',
  'Morgott, The Omen King, is a Demigod Boss found in Leyndell, Royal Capital. He is the true identity of Margit, the Fell Omen.',
  'Morgott defended the Golden Order even while imprisoned for being an Omen royalty, revealing his loyalty despite his outcast status.',
  '{"Phase 1": {"Holy Swords Rain": "Spawns holy swords in the air.", "Tail Sweep": "Sweeps with his tail."}, "Phase 2": {"Cursed Explosion": "Unleashes a curse, spawning geysers.", "Holy Spear Throw": "Throws a holy spear."}}',
  '{"ng": {"hp": 10399, "defense": 114, "runes": 120000}, "ng_plus": {"hp": 13029, "defense": 118, "runes": 360000}}',
  '{"lat": 51.5074, "lng": -0.1278}' 
),
(
  21, 'Mohg, Lord of Blood', 'Mohgwyn Palace', TRUE, 18389,
  '420,000 Runes, Mohg\'s Great Rune, Remembrance of the Blood Lord', 'Dynasty Mausoleum Midpoint',
  'Standard, Pierce, Fire', 122, 110, FALSE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 10, "Magic": 40, "Fire": 80, "Lightning": 40, "Holy": 40}', 
  '{"Poison": 653, "Scarlet Rot": 653, "Hemorrhage": 290, "Frostbite": 653, "Sleep": 1406, "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/mohg.jpg', 
  'https://img.game8.co/3503657/da1cd435ac4dbbe28b976c0ac88bb670.png/show', 
  'https://www.youtube.com/watch?v=hqCRSfHRfb8&ab_channel=EvilCouncilGaming',
  'Mohg, Lord of Blood, is a Demigod Boss found in Mohgwyn Palace. This Omen demigod specializes in blood magic, using bloodflame magic after encountering the Formless Mother.',
  'Mohg aims to rise to king consort by raising Miquella to godhood. He must be defeated to access the Shadow of the Erdtree DLC.',
  '{"Phase 1": {"Bloodflame Talons": "Quick slash followed by explosive burst.", "Bloodboon": "Launches bloodflame that ignites the ground."}, "Phase 2": {"Blood Tax": "Inflicts damage and builds hemorrhage.", "Blood Curse": "Drains HP and deals bleed damage."}}',
  '{"ng": {"hp": 18389, "defense": 122, "runes": 420000}, "ng_plus": {"hp": 18664, "defense": 123, "runes": 840000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  
),
(
  22, 'Radagon of the Golden Order', 'Elden Throne', FALSE, 13339,
  'Remembrance of the Elden Lord', 'The Elden Throne',
  'Standard, Strike, Holy', 121, 120, TRUE, 'Stance Broken',
  '{"Standard": 35, "Slash": 35, "Strike": 10, "Pierce": 35, "Magic": 20, "Fire": 0, "Lightning": 20, "Holy": 80}', 
  '{"Poison": 627.4, "Scarlet Rot": 627.4, "Hemorrhage": "Immune", "Frostbite": 627.4, "Sleep": "Immune", "Madness": "Immune"}',
  'https://dotesports.com/wp-content/uploads/2022/04/07091356/eldenring.exe-Screenshot-2022.03.15-10.29.39.46-e1649340871882.png', 
  'https://img.game8.co/3504357/990f8461ca1187ed539355203976eec9.png/show', 
  'https://www.youtube.com/watch?v=2fuH7TckQWI&ab_channel=TheAbysswalker',
  'Radagon of the Golden Order is a mandatory boss in Elden Ring, encountered at the Elden Throne. He wields the hammer that shattered the Elden Ring and transforms into the Elden Beast upon defeat.',
  'Radagon is the other half of Queen Marika, attempting to repair the Elden Ring after it was shattered.',
  '{"Holy Spear Throw": "Throws a holy spear that lingers before exploding.", "Golden Breaker": "Leaps into the air and slams down with a golden explosion.", "Parry Stance": "Raises arm to deflect attacks."}',
  '{"ng": {"hp": 13339, "defense": 121, "runes": 500000}, "ng_plus": {"hp": 14688, "defense": 123, "runes": 1500000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  
),
(
  23, 'Elden Beast', 'Elden Throne', FALSE, 22127,
  'Remembrance of the Elden Beast', 'The Elden Throne',
  'Standard, Pierce, Holy', 150, 150, FALSE, 'Stance Broken',
  '{"Standard": 10, "Slash": 10, "Strike": 10, "Pierce": 10, "Magic": 40, "Fire": 40, "Lightning": 40, "Holy": 80}', 
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "Immune", "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/elden-beast-boss-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3505084/dc910e3ede974f8ac431b279904dd88b.png/show', 
  'https://www.youtube.com/watch?v=5akj_UFLVPI&ab_channel=JTTV%28JTGaming%29',
  'Elden Beast is the true form of the Elden Ring, acting as the vassal of the Greater Will, and is found in the Elden Throne. It is not an optional boss and is the final fight of the game.',
  'The Elden Beast represents the living incarnation of the concept of Order and was sent to the Lands Between through a golden star.',
  '{"Hand Slam": "Slams its left hand into the ground.", "Golden Breath": "Spews out yellow fire.", "Sword Swing": "Swings its sword.", "Swimming Sword Swing": "Returns with a large sword swing."}',
  '{"ng": {"hp": 22127, "defense": 150, "runes": 500000}, "ng_plus": {"hp": 24100, "defense": 160, "runes": 1500000}}',
  '{"lat": 51.509865, "lng": -0.118092}'  
),
(
  24, 'Death Knight', 'Fog Rift Catacombs', TRUE, 21150,
  '110,000 Runes, Death Knight\'s Twin Axes, Crimson Amber Medallion +3', 'Fog Rift Catacombs',
  'Standard, Lightning', 100, 80, TRUE, 'Stance Broken',
  '{"Standard": 20, "Slash": 20, "Strike": 20, "Pierce": 20, "Magic": 40, "Fire": 40, "Lightning": 40, "Holy": 40}', 
  '{"Poison": "Immune", "Scarlet Rot": "Immune", "Hemorrhage": "Immune", "Frostbite": "Immune", "Sleep": "Immune", "Madness": "Immune"}',
  'https://i.ytimg.com/vi/3Cp4pHcTj2c/maxresdefault.jpg', 
  'https://img.game8.co/3914838/60fce7d8e6ffd6e21a3d7b61ef873a10.png/show', 
  'https://www.youtube.com/watch?v=3Cp4pHcTj2c&ab_channel=BossFightDatabase',
  'Death Knight is a Great Enemy Boss found in the Fog Rift Catacombs. This optional boss wields various weapons that can conjure lightning.',
  'The Death Knight is a powerful entity encountered in multiple locations, known for its high resilience and lightning-based attacks.',
  '{"Axe Spin": "Spins with lightning-imbued axes.", "Axe Swing": "Swings axes in different directions.", "Deadly Dash": "Dashes forward to grab and stab repeatedly.", "Lightning Bolt": "Creates orbs of lightning to strike."}',
  '{"ng": {"hp": 21150, "defense": 100, "runes": 110000}, "ng_plus": {"hp": 23000, "defense": 110, "runes": 330000}}',
  '{"lat": 34.0522, "lng": -118.2437}'  
),
(
  25, 'Crucible Knight Ordovis', 'Auriza Hero\'s Grave', TRUE, 5460,
  '28,000 Runes, Ordovis\'s Greatsword, Crucible Axe Set', 'Auriza Hero\'s Grave',
  'Standard, Pierce, Holy', 111, 80, TRUE, 'Stance Broken',
  '{"Standard": 35, "Slash": 35, "Strike": 35, "Pierce": 35, "Magic": 40, "Fire": 20, "Lightning": 20, "Holy": 40}', 
  '{"Poison": 543, "Scarlet Rot": 543, "Hemorrhage": "Immune", "Frostbite": 543, "Sleep": 543, "Madness": "Immune"}',
  'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crucible-knight-and-ordovis-1-hq-elden-ring-wiki-guide.jpg', 
  'https://img.game8.co/3517654/b2a04c95712ee867b3eb6229843d68f2.png/show', 
  'https://www.youtube.com/watch?v=pW8-_rb6x7Y&ab_channel=Shirrako',
  'Crucible Knight Ordovis is a heavy and large knight found in Auriza Hero\'s Grave. Wields a greatsword and a shield, can materialize wings and fly.',
  'Ordovis is honored as one of the foremost among the Crucible Knights.',
  '{"Axe Slam": "Slams axe into the ground creating a shockwave.", "Wing Attack": "Materializes wings to attack."}',
  '{"ng": {"hp": 5460, "defense": 111, "runes": 28000}, "ng_plus": {"hp": 7977, "defense": 118, "runes": 84000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  
  ),
(
  26, 'Flying Dragon Greyll', 'Farum Greatbridge', TRUE, 11550,
  '80,000 Runes, Dragon Heart', 'Farum Greatbridge',
  'Standard, Fire', 121, 120, FALSE, 'Stance Broken',
  '{"Standard": 35, "Slash": 35, "Strike": 35, "Pierce": 10, "Magic": 40, "Fire": 40, "Lightning": 40, "Holy": 40}', 
  '{"Poison": 627, "Scarlet Rot": 627, "Hemorrhage": 627, "Frostbite": 627, "Sleep": "Immune", "Madness": "Immune"}',
  'https://oyster.ignimgs.com/mediawiki/apis.ign.com/elden-ring/c/c2/Elden_DragonB_GreyllDragon.jpg', 
  'https://img.game8.co/3513645/55dd6099ba8412ca2960e5c4eccb5e8f.png/show', 
  'https://www.youtube.com/watch?v=hhOe6vAh7CU&ab_channel=Esoterickk',
  'Flying Dragon Greyll is a Greater Foe Boss found guarding the bridge south of the Bestial Sanctum. This is an optional boss known for its powerful fire attacks.',
  'Flying Dragon Greyll is simply a stronger version of Flying Dragon Agheel, found in a rather narrow arena on the bridge.',
  '{"Fire Breath": "Breathes fire in a wide arc.", "Claw Swipe": "Swipes with its claws.", "Tail Swipe": "Swings its tail in a wide arc.", "Bite": "Bites with its powerful jaws."}',
  '{"ng": {"hp": 11550, "defense": 121, "runes": 80000}, "ng_plus": {"hp": 12717, "defense": 123, "runes": 160000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  
),
(
  27, 'Dragonlord Placidusax', 'Crumbling Farum Azula', TRUE, 26651,
  '280,000 Runes, Remembrance of the Dragonlord', 'Beside the Great Bridge',
  'Standard, Fire, Lightning', 121, 160, FALSE, 'Stance Broken',
  '{"Standard": 35, "Slash": 35, "Strike": 35, "Pierce": 10, "Magic": 40, "Fire": 40, "Lightning": 40, "Holy": 40}', 
  '{"Poison": 1349, "Scarlet Rot": 1349, "Hemorrhage": 1349, "Frostbite": 1349, "Sleep": "Immune", "Madness": "Immune"}',
  'https://i.ytimg.com/vi/Xc5jJvPOeWo/maxresdefault.jpg', 
  'https://img.game8.co/3505024/4f36a79f2db6ec78efa08c172ac714a9.png/show', 
  'https://www.youtube.com/watch?v=jvNQeH3Y6f4&ab_channel=AlexFish',
  'Dragonlord Placidusax is a massive, two-headed dragon found in Crumbling Farum Azula. This optional boss was once an Elden Lord before the reign of Marika and the Golden Order.',
  'Placidusax ruled alongside his god, who later fled, leaving him to await its return.',
  '{"Phase 1": {"Lightning Strike": "Summons large AOE lightning bolts.", "Claw Swipe": "Slashes with lightning-imbued claws."}, "Phase 2": {"Dive Attack": "Dives from storm clouds for a fast attack.", "Fire Breath": "Spews flames or lasers from both heads."}}',
  '{"ng": {"hp": 26651, "defense": 121, "runes": 280000}, "ng_plus": {"hp": 26677, "defense": 120, "runes": 560000}}',
  '{"lat": 35.6895, "lng": 139.6917}'  -- Exemple de coordonnées pour Tokyo, à remplacer par les vraies coordonnées
);


